name: profile-metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: github-metrics
          committer_message: "Action: update `${filename}`"

          user: abrahamnm
          config_timezone: "America/Monterrey"
          template: classic

          base: header
          repositories_affiliations: owner, collaborator

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_languages: yes
          plugin_languages_details: byte-size, percentage

          plugin_isocalendar: yes

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered

          plugin_lines: yes

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 180
          plugin_wakatime_sections: languages, languages-graphs, editors, os
