name: Update twitter header

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

jobs:
  twitter_update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update twitter header
        uses: abrahamnm/twitter-header@v1.0.0
        with:
          header_path: header.png
          api_key: ${{ secrets.API_KEY }}
          api_secret: ${{ secrets.API_SECRET }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
